import { DimensionValue, ViewProps } from "react-native";
import { RadiusTypes, SpacingTypes, ThemeColorType } from "theme";

export type StackProps = ViewProps & {
  children?: React.ReactNode;
  direction?: "row" | "column" | "row-reverse" | "column-reverse";
  justify?: "center" | "flex-start" | "flex-end" | "space-between" | "space-around" | "space-evenly";
  jc?: "center" | "flex-start" | "flex-end" | "space-between" | "space-around" | "space-evenly";
  align?: "center" | "flex-start" | "flex-end" | "stretch" | "baseline";
  ai?: "center" | "flex-start" | "flex-end" | "stretch" | "baseline";
  alignSelf?: "center" | "flex-start" | "flex-end" | "stretch" | "baseline";
  padding?: SpacingTypes;
  pa?: SpacingTypes;
  px?: SpacingTypes;
  py?: SpacingTypes;
  pt?: SpacingTypes;
  pb?: SpacingTypes;
  pr?: SpacingTypes;
  pl?: SpacingTypes;
  margin?: SpacingTypes;
  ma?: SpacingTypes;
  mx?: SpacingTypes;
  my?: SpacingTypes;
  mt?: SpacingTypes;
  mb?: SpacingTypes;
  mr?: SpacingTypes;
  ml?: SpacingTypes;
  backgroundColor?: ThemeColorType;
  bc?: ThemeColorType;
  borderRadius?: RadiusTypes;
  borderColor?: ThemeColorType;
  borderWidth?: number;
  br?: RadiusTypes;
  gap?: SpacingTypes;
  full?: boolean;
  flex?: number;
  width?: DimensionValue | undefined;
  w?: DimensionValue | undefined;
  height?: DimensionValue | undefined;
  h?: DimensionValue | undefined;
  maxWidth?: DimensionValue | undefined;
  maxHeight?: DimensionValue | undefined;
  x?: DimensionValue | undefined;
  y?: DimensionValue | undefined;
  z?: number;
  position?: "absolute" | "relative";
  flexGrow?: number | boolean;
  flexShrink?: number | boolean;
  shadow?: boolean;
  wrap?: boolean;
  flexWrap?: "wrap" | "nowrap" | "wrap-reverse";
};
